base_url = "https://emilio.co.za"
compile_sass = true
build_search_index = false

[markdown]
highlight_code = true

[link_checker]
internal_level = "error"
external_level = "error"

[extra]
# Put all your custom variables here
