title = "Emilio Ziniades"
author = "Emiio Ziniades"
base_url = "https://emilio.co.za"

compile_sass = false
build_search_index = false
theme = "zola-bearblog"

taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]

default_language = "en"

[translations]
no_posts = "No posts yet"
remove_filter = "Remove filter"
filtering_for = "Filtering for"
made_with = "Made with"
site = "site"
table_of_contents = "Table of contents"

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "gruvbox-dark", filename = "syntax-theme-dark.css" },
  { theme = "gruvbox-light", filename = "syntax-theme-light.css" },
]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "error"
external_level = "error"

[extra.table_of_contents]
show = true
max_level = 4
visible_on_load = true

[[extra.main_menu]]
name = "Home"
url = "/"

[[extra.main_menu]]
name = "Blog"
url = "@/blog/_index.md"

[[extra.main_menu]]
name = "Open-source"
url = "@/open-source.md"

[[extra.main_menu]]
name = "About"
url = "@/about.md"
