[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.20.0"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"

[[headers]]
for = "/*"
[headers.values]
# see https://content-security-policy.com/
Content-Security-Policy = "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self' 'sha256-p5EfRIhWJi7Zh7WJil3mpIVCZvcu+zebWbMe6B0so8A=';base-uri 'self';form-action 'self'"
